coverage:
  status:
    project:
      default:
        target: auto
        paths:
          - "packages/relic_core/**"
          - "packages/relic_io/**"
          - "packages/relic/**"
    patch:
      default:
        target: auto
        paths:
          - "packages/relic_core/**"
          - "packages/relic_io/**"
          - "packages/relic/**"

ignore:
  - "packages/examples/**"
  - "packages/benchmark/**"
  - "doc/**"

flag_management:
  individual_flags:
    - name: relic_core
      paths:
        - packages/relic_core/
      carryforward: true
    - name: relic_io
      paths:
        - packages/relic_io/
      carryforward: true
    - name: relic
      paths:
        - packages/relic/
      carryforward: true
